[appearance]
font_name = "RobotoMono Nerd Font"
style = "Solid"

success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = ["#89b4fa", "#11111b", "#cdd6f4"]

[appearance.primary_color]
base = "#89b4fa"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#11111b"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
